# Generated by Django 5.2.15 on 2026-06-24 23:48

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Secure universally unique identifier substituting standard integers.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp automatically recorded upon database record initialization.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp automatically overwritten whenever row values change.",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        help_text="International format string used as the webhook lookup key (e.g., +2348012345678)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("yo", "Yoruba"),
                            ("ha", "Hausa"),
                            ("ig", "Igbo"),
                        ],
                        default="en",
                        help_text="Preferred language code for outbound automated WhatsApp message routing",
                        max_length=2,
                    ),
                ),
                (
                    "flock_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The latest known total number of poultry birds on the farm (Acts as current baseline)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="State or local region in Nigeria where the poultry farm is located",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Flips to True once the initial profile data gathering script is fully complete",
                    ),
                ),
                (
                    "consent_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="NDPR Privacy compliance toggle. Must be set to True before processing health telemetry data",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farmer Profile",
                "verbose_name_plural": "Farmer Profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
