# Generated by Django 5.2.15 on 2026-06-25 05:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Secure universally unique identifier substituting standard integers.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp automatically recorded upon database record initialization.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp automatically overwritten whenever row values change.",
                    ),
                ),
                (
                    "current_flock_size",
                    models.PositiveIntegerField(
                        help_text="The total number of live birds present on the farm during this interaction",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "birds_affected",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of birds currently exhibiting symptoms of illness",
                    ),
                ),
                (
                    "birds_dead",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of sudden mortalities recorded in this current disease window",
                    ),
                ),
                (
                    "symptoms_reported",
                    models.TextField(
                        help_text="The raw text or transcript submitted by the farmer describing poultry health anomalies"
                    ),
                ),
                (
                    "ai_diagnosis",
                    models.TextField(
                        blank=True,
                        help_text="The structural analytical output generated by our downstream clinical engine",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending AI Processing"),
                            ("processed", "Completed Diagnosis"),
                            ("failed", "System Processing Failure"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        help_text="The specific farmer profile associated with this health query history log",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="farmers.farmer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation Event Log",
                "verbose_name_plural": "Consultation Event Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
