# apps/consultations/models.py
from django.db import models
from django.core.validators import MinValueValidator
from apps.core.models import BaseModel

class ConsultationLog(BaseModel):
    
    STATUS_CHOICES = [
        ('pending', 'Pending AI Processing'),
        ('processed', 'Completed Diagnosis'),
        ('failed', 'System Processing Failure'),
    ]

    # One to Many relationship to connect this event log immutably to our Farmer profile
    farmer = models.ForeignKey(
        'farmers.Farmer',
        on_delete=models.CASCADE,
        related_name='consultations',
        db_index=True, # Explicit index for rapid historical lookups per farmer
        help_text="The specific farmer profile associated with this health query history log"
    )

    # Captures the moving numbers on this exact day
    current_flock_size = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        help_text="The total number of live birds present on the farm during this interaction"
    )
    
    birds_affected = models.PositiveIntegerField(
        default=0,
        help_text="The number of birds currently exhibiting symptoms of illness"
    )
    
    birds_dead = models.PositiveIntegerField(
        default=0,
        help_text="The number of sudden mortalities recorded in this current disease window"
    )

    # The medical details
    symptoms_reported = models.TextField(
        help_text="The raw text or transcript submitted by the farmer describing poultry health anomalies"
    )
    
    ai_diagnosis = models.TextField(
        null=True, 
        blank=True,
        help_text="The structural analytical output generated by our downstream clinical engine"
    )

    # STATE CONTROL
    status = models.CharField(
        max_length=15,
        choices=STATUS_CHOICES,
        default='pending',
        db_index=True
    )

    class Meta:
        ordering = ['-created_at']
        verbose_name = "Consultation Event Log"
        verbose_name_plural = "Consultation Event Logs"

    def __str__(self):
        return f"Case {self.id[:8]}... | Farmer: {self.farmer.phone_number} | Status: {self.status}"
